version: '3.2'

services:
  php:
    container_name: test_php
    expose:
      - 9000
    build: .
    volumes:
      - .:/var/www

  redis:
    container_name: test_redis
    image: "redis:alpine"
    ports:
    - "6379:6379"
    volumes:
        - $PWD/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf